// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB0_rRCfoX4qF2Fzb2s2VzndTtjfuO2tE',
    appId: '1:533926334077:web:1c832e9f8abc80e4fa2b14',
    messagingSenderId: '533926334077',
    projectId: 'cema-task',
    authDomain: 'cema-task.firebaseapp.com',
    storageBucket: 'cema-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGMmcrmsg-8vbOnwwpY87ZdNe6tfZUFKI',
    appId: '1:533926334077:android:aeab490a4db9a692fa2b14',
    messagingSenderId: '533926334077',
    projectId: 'cema-task',
    storageBucket: 'cema-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwfUsWot_38Ac3wBhsMWwC-vfVwmCESz4',
    appId: '1:533926334077:ios:1495377a4ee399cdfa2b14',
    messagingSenderId: '533926334077',
    projectId: 'cema-task',
    storageBucket: 'cema-task.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwfUsWot_38Ac3wBhsMWwC-vfVwmCESz4',
    appId: '1:533926334077:ios:631c7b0b8ac3aae0fa2b14',
    messagingSenderId: '533926334077',
    projectId: 'cema-task',
    storageBucket: 'cema-task.appspot.com',
    iosBundleId: 'com.example.task.RunnerTests',
  );
}
